pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests -Denforcer.skip=true clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn -Denforcer.skip=true -Denforcer.skip=true test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Final-Pipeline-1') {
            steps {
                echo 'Final Job Pipeline-1'
            }
        }
        stage('Complete') {
            steps {
                echo 'Job Completion'
            }
        }
    }
}
